runtime: nodejs14

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|png|svg|txt))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png|svg|txt)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
