name: Deploy to GCP
on: [push]
jobs:
  env:
    client-directory: ./client
    server-directory: ./server
  Deploy-Client:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: yarn build
        working-directory: ${{ env.client-directory }}

      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
        working-directory: ${{ env.client-directory }}

      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"
        working-directory: ${{ env.client-directory }}
