name: Deploy to GCP
on: [push]
jobs:
  Deploy-Client:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: yarn build
        working-directory: ./client

      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          working-directory: ./client

      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"
        working-directory: ./client
