name: Deploy to GCP
on: [push]
jobs:
  Deploy-Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: cd ./client && yarn install

      - name: Run Tests
        run: cd ./client && yarn test --watchAll=false

      - name: Run Build
        run: cd ./client && yarn build

      - id: deploy
        name: Deploy to Google app engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./client

      - name: Check deployment succeeded
        run: curl "${{ steps.deploy.outputs.url }}"
        working-directory: ./client

  Deploy-Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup Database Secret
        run: echo "DB_URI=${{ secrets.DB_URI }}" > server/.env

      - name: Install Dependencies
        run: cd ./server && yarn install

      - name: Run Tests
        run: cd ./server && yarn test

      - name: Run Build
        run: cd ./server && yarn build

      - id: deploy
        name: Deploy to Google app engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./server

      - name: Check deployment succeeded
        run: curl "${{ steps.deploy.outputs.url }}"
        working-directory: ./server
