name: Deploy to GCP
on: [push]
jobs:
  Deploy-Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd ./client install
          
          
      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd ./client build

      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./client

      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"
        working-directory: ./client
