name: Run Tests
on:
  push:
    branches:
      - "*"
      - "!main"
jobs:
  Test-Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: yarn install
        working-directory: ./client

      - name: Run Tests
        run: yarn test --watchAll=false
        working-directory: ./client

  Test-Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup Database Secret
        run: echo "DB_URI=${{ secrets.DB_URI }}" > server/.env

      - name: Install Dependencies
        run: yarn install
        working-directory: ./server

      - name: Run Tests
        run: yarn test
        working-directory: ./server
